CREATE TABLE PESSOA
(

    ID                BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NOME              VARCHAR(255),
    IDENTIFICADOR  VARCHAR(20),
    DATANASCIMENTO    VARCHAR(255),
    TIPOIDENTIFICADOR VARCHAR(2),
    VALORMIN          DECIMAL,
    VALORMAX          DECIMAL

);